name: update-details

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-details:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python 3.7 Env
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Update podcast details
        run: python episodes.py

      - name: Push updates to the repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update: Auto podcast updates for `date`"
          git push

      - name: Update podarts
        run: python podart.py

      - name: Push updates to the repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update: Auto podart updates for `date`"
          git push
